apiVersion: v1
kind: Service
metadata:
  name: car-history
  labels:
    app: car-history
    spring-boot: "true"
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8185"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: actuator
      port: 8185
      targetPort: 8185

  selector:
    app: car-history
  type: ClusterIP


