server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
      enabled: false
    gateway:
      routes:
        - id: user-service-route
          # lb://user-service:8082
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /user/$\{segment}

        - id: auth-service-route
          # lb://auth-service:8086
          uri: http://127.0.0.1:8086
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}

        - id: mail-process-service-route
          # lb://mail-process-service:8084
          uri: http://127.0.0.1:8084
          predicates:
            - Path=/api/mail/**
          filters:
            - RewritePath=/api/mail/(?<segment>.*), /mail/$\{segment}
        - id: car-history-service-route
          # lb://car-history-service:8085
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/api/car/**
          filters:
            - RewritePath=/api/car/(?<segment>.*), /$\{segment}
            - AuthenticationFactory
      globalcors:
        corsConfigurations:
          '[/api/**]':
            allowedOrigins:
              - http://localhost:4200
              - http://127.0.0.1:4200
              - http://localhost:8080
              - http://127.0.0.1:8080
              - http://localhost:4200
              - http://127.0.0.1:4200
              - https://mail.nullchefo.com
              - https://nullchefo.com
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
management:
  endpoints:
    web:
      exposure:
        include: '*'


auth:
  accessTokenSecret: exampleTokenSecret


