server:
  port: 8083
  shutdown: graceful
  error:
    include-message: always
    include-exception: true # TODO make it false

spring:
  application:
    name: mail-send-service
  datasource:
    url:
    username:
    password:
  rabbitmq:
    addresses:
    port:
    username:
    password:
    # host: 127.0.0.1
  jpa:
    hibernate:
      # TODO make validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    # TODO make true
  flyway:
    enabled: false

#  cloud:
#    kubernetes:
#      discovery:
#        # TODO change false
#        all-namespaces: true
#      loadbalancer:
#        mode: service
#        enabled: true
#      enabled: true
#    loadbalancer:
#      ribbon:
#        enabled: false
  # TODO ADD YOUR EMAIL CREDENTIALS
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          protocols: TLSv1.2
        starttls:
          enable: true
    default-encoding: UTF-8

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


rabbitmq:
  queue:
    name: mail-send-queue
  exchange:
    name: mail-send-exchange
  routing:
    key: mail-send-routing-key

