
FROM ghcr.io/graalvm/graalvm-ce:ol8-java17-22.2.0 AS build

RUN gu install native-image

RUN mkdir /build

RUN COPY ./target/user-service-0.0.1-SNAPSHOT.jar /build/app.jar

RUN cd /build && native-image --static -jar app.jar


FROM scratch

RUN COPY --from=build /build/app /opt/app
CMD ["/opt/app"]
