apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: user-service
build:
  artifacts:
    - image: docker.io/nullchefo/user-service
#    - jib: {}

  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - ../k8s/mysql.yaml
      - ../k8s/user-service-app.yaml

