apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-configmap
data:

  #  SPRING_PROFILES_ACTIVE: kubernetes

  SERVER_PORT: "9000"
  ZIPKIN_URL: "http://tempo.monitoring.svc:9411"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.monitoring.svc:9411"
  LOKI_URL: "http://loki.monitoring.svc:3100/loki/api/v1/push"
  FE_ADDRESS: "https://diploma-project.nullchefo.com"
