apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  #  SPRING_PROFILES_ACTIVE: kubernetes
  FE_ADDRESS: "https://diploma-project.nullchefo.com"
  ZIPKIN_URL: "http://tempo.monitoring.svc:9411"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.monitoring.svc:9411"
  AUTHORIZATION_SERVER_URL: "http://authorization:9000"
  AUTHORIZATION_SERVER_ISSUER_URL: "https://auth.nullchefo.com"
  LOKI_URL: "http://loki.monitoring.svc:3100/loki/api/v1/push"
