apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    spring-boot: "true"
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8182"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    #      protocol: TCP
    - name: actuator
      port: 8182
      targetPort: 8182
