apiVersion: v1
kind: Service
metadata:
  name: mail-process
  labels:
    app: mail-process
    spring-boot: "true"
spec:
  selector:
    app: mail-process
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
#      protocol: TCP
