---
version: '3'
services:

  ## Mysql database
  mysql:
    container_name: mysql-db
    image: mysql:latest
    volumes:
      - ~/.docker-conf/mysql/v1/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pAssSwO0RDyy?
      MYSQL_DATABASE: diploma_project
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped


  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    expose:
      - "9411"
    ports:
      - "9411:9411"
    restart: unless-stopped


  ## Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

  ## Gateway-Service Docker Compose Config
  gateway-service:
    container_name: gateway-service
    image: docker.io/nullchefo/gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9001
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    expose:
      - "9001"
    ports:
      - "9001:9001"

  ## Auth-History-Service Docker Compose Config
  auth-service:
    container_name: auth-service
    image: docker.io/nullchefo/auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=15672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SERVER_PORT=9002
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "9002:9002"


  ## User-Service Docker Compose Config
  user-service:
    container_name: user-service
    image: docker.io/nullchefo/user-service
    environment:
        # when specify profile "docker" that means to get the application-docker.yml
        # if it was SPRING_PROFILES_ACTIVE=prod it will pull application-prod.yml
        # - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=15672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SERVER_PORT=9003
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "9003:9003"

  ## Mail-Process-Service Docker Compose Config
  mail-process-service:
    container_name: mail-process-service
    image: docker.io/nullchefo/mail-process-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=15672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SERVER_PORT=9004
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    #    depends_on:
    #      - mysql
    #      - rabbitmq
    ports:
      - "9004:9004"




  ## Mail-Send-Service Docker Compose Config
  mail-send-service:
    container_name: mail-send-service
    image: docker.io/nullchefo/mail-send-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=15672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password

      - SPRING.MAIL.HOST=smtp.gmail.com
      - SPRING.MAIL.PORT=587
      - SPRING.MAIL.USERNAME=pu.diploma.project@gmail.com
      - SPRING.MAIL.PASSWORD=itrfksxhfmtydwqw
      - SPRING.MAIL.properties.mail.smtp.auth=true
      - SPRING.MAIL.properties.mail.smtp.starttls.enable=true
      - SPRING.MAIL.defaultEncoding=UTF-8
      - mail.smtp.ssl.trust=smtp.gmail.com
      - spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
      - SERVER_PORT=9005
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
   # depends_on:
   #   - mysql
   #   - rabbitmq
    ports:
      - "9005:9005"
    expose:
      - "587"
      - "465"

  ## Car-History-Service Docker Compose Config
  car-history-service:
    container_name: car-history-service
    image: docker.io/nullchefo/car-history-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq
      - SPRING_RABBITMQ_PORT=15672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SERVER_PORT=9006
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "9006:9006"

