apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    spring-boot: "true"
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
#      protocol: TCP
