apiVersion: v1
kind: Service
metadata:
  name: social-media
  labels:
    app: social-media
    spring-boot: "true"
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8192"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 8092
      targetPort: 8092

    - name: actuator
      port: 8192
      targetPort: 8192

  selector:
    app: social-media
  type: ClusterIP


