apiVersion: v1
kind: Service
metadata:
  name: mail-send
  labels:
    app: mail-send
    spring-boot: "true"
spec:
  selector:
    app: mail-send
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
#      protocol: TCP
