apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    app: tempo
  ports:
    - name: tempo-not-default
      port: 3100
      targetPort: 3100

    - name: jaeger-ingest
      port: 14268
      targetPort: 14268

    - name: open-telemetry-http
      port: 4318
      targetPort: 4318

    - name: zipkin
      port: 9411
      targetPort: 9411

    - name: tempo
      port: 3200
      targetPort: 3200

    - name: open-telemetry-grpc
      port: 4317
      targetPort: 4317

  type: ClusterIP
