server:
  port: 8086
  shutdown: graceful
  error:
    include-message: always
    include-exception: true # TODO make it false

spring:
  application:
    name: auth-service
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses:
    port:
    username:
    password:
  zipkin:
    enabled: true
    base-url:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


rabbitmq:
  queue:
    name: mail-process-queue
  exchange:
    name: mail-process-exchange
  routing:
    key: mail-process-routing-key


auth:
  accessTokenSecret: exampleTokenSecret
  refreshTokenSecret: exampleRefreshTokenSecret
  accessTokenDurationMinutes: 600
  refreshTokenDurationMinutes: 1200
  accessTokenCookieName: accessToken
  refreshTokenCookieName: refreshToken


frontEnd:
  # TODO change for prod
  url: http://localhost:4200/

env:
  prod: false
