server:
  port: 9000
  shutdown: graceful
  error:
    include-stacktrace: always

  #    include-message: always
  # TODO make it false
#    include-exception: true
#    include-stacktrace: always
#    whitelabel:
#      enabled: on

spring:
  application:
    name: authorization-service
  output.ansi.enabled: ALWAYS

  data:
    redis:
      host: ${REDIS_HOST:localhost}
    #      username: ${REDIS_USERNAME:username}
    #      password: ${REDIS_PASSWORD:username}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/diploma-project}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:rootpassword}
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESS:127.0.0.1}
    port: ${RABBITMQ_POST:15672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    # host: 127.0.0.1
  jpa:
    hibernate:
      # TODO make validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    # TODO make true
  flyway:
    enabled: false
  # Security
  security:
    oauth2:
      client:
        registration:
          apple-idp:
            provider: apple
            client-id: ${APPLE_CLIENT_ID:apple_id}
            client-secret: ${APPLE_CLIENT_SECRET:apple_secret}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
            scope: openid,name,email
            client-name: Apple
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google_secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github_id}
            client-secret: ${GITHUB_CLIENT_SECRET:github_secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
          facebook-idp:
            provider: facebook
            clientId: ${FACEBOOK_CLIENT_ID:facebook_id}
            clientSecret: ${FACEBOOK_CLIENT_SECRET:facebook_secret}
            scope:
              - email
              - public_profile
            client-name: Sign in with Facebook



        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
          facebook:
            user-name-attribute: email

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
## Only for debugging purposes
#  level:
#    root: INFO
#    org.springframework.web: TRACE
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.security.jwt: TRACE

management:
  server:
    # actuator port
    port: 9100
  #  server:
  #    port: 8081
  #    ssl:
  #      enabled: false

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:"http://localhost:9411"}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 3s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true


address:
  frontEnd:
    baseURL: https://diploma-project-ui.nullchefo.com
    successfullyLogOut: https://diploma-project-ui.nullchefo.com/auth/logged-out

springdoc:
  api-docs:
    path: /v1/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-client
