apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  labels:
    app: authorization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authorization
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: docker.io/nullchefo/authorization-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              # after 1.7GB the GC is much better
              # TODO add the JAVA GC talk link
              memory: "1843Mi"
              cpu: "2000m"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: authorization-configmap
            - secretRef:
                name: authorization-secret
