apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: docker.io/nullchefo/auth-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              # after 1.7GB the GC is much better
              memory: "1843Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
