apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://127.0.0.1:5432/project"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: ""

  SPRING_RABBITMQ_ADDRESSES: "rabbitmq"
  SPRING_RABBITMQ_PORT: "15672"
  SPRING_RABBITMQ_USERNAME: "user"
  SPRING_RABBITMQ_PASSWORD: ""

type: Opaque
