apiVersion: v1
kind: Service
metadata:
  name: mail-process
  labels:
    app: mail-process
    spring-boot: "true"
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8184"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: mail-process
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    #      protocol: TCP
    - name: actuator
      port: 8184
      targetPort: 8184
