apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-configmap
  namespace: monitoring
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      grpc_server_max_recv_msg_size: 8388608
      grpc_server_max_send_msg_size: 8388608
    
    clients:
      - url: 'http://loki.monitoring.svc:3100/loki/api/v1/push'
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log
              node_name: '${HOSTNAME}'
