apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:main-4e893a0
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"

          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-configmap
