apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  ports:
    - port: 9080
      targetPort: 9080
  type: ClusterIP
