FROM azul/zulu-openjdk-alpine:17-latest as deps

 # TODO change
# Identify dependencies
COPY ./target/mail-process-service-0.0.1-SNAPSHOT.jar /app/app.jar

RUN mkdir /app/unpacked && \
    cd /app/unpacked && \
    unzip ../app.jar && \
    cd .. && \
    $JAVA_HOME/bin/jdeps \
    --ignore-missing-deps \
    --print-module-deps \
    -q \
    --recursive \
    --multi-release 17 \
    --class-path="./unpacked/BOOT-INF/lib/*" \
    --module-path="./unpacked/BOOT-INF/lib/*" \
    ./app.jar > /deps.info

# -------------------------------------------------------------

# base image to build a JRE

#FROM openjdk:19-alpine as openjdk

FROM azul/zulu-openjdk-alpine:17-latest as openjdk


# required for strip-debug to work
RUN apk add --no-cache binutils

# copy module dependencies info
COPY --from=deps /deps.info /deps.info

# Build small JRE image
RUN $JAVA_HOME/bin/jlink \
    --verbose \
    --add-modules $(cat /deps.info) \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /customjre

# main app image
FROM alpine:latest
ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# copy JRE from the base image
COPY --from=openjdk /customjre $JAVA_HOME

# Add app user
ARG APPLICATION_USER=appuser
RUN adduser --no-create-home -u 1000 -D $APPLICATION_USER

# Configure working directory
RUN mkdir /app && \
    chown -R $APPLICATION_USER /app

USER 1000
 # TODO change
COPY --chown=1000:1000 ./target/mail-process-service-0.0.1-SNAPSHOT.jar /app/app.jar
WORKDIR /app

 # TODO change
EXPOSE 8084
ENTRYPOINT [ "/jre/bin/java", "-Xmx2G", "-jar", "/app/app.jar" ]
