server:
  port: 8082
  shutdown: graceful
  error:
    include-message: always
    include-exception: true # TODO make it false

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: 127.0.0.1
    port: 15672
    username: user
    password: password
   # host: 127.0.0.1
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      # TODO read more https://www.springcloud.io/post/2022-05/spring-cloud-kubernetes/#gsc.tab=0

management:
  endpoints:
    web:
      exposure:
        # TODO *
        include: prometheus

rabbitmq:
  queue:
    name: mail-process-queue
  exchange:
    name: mail-process-exchange
  routing:
    key: mail-process-routing-key

frontEnd:
  # TODO change for prod
  url: http://localhost:4200

env:
  prod: false


services-list:
  auth-service: "http://localhost:9002"
  mail-process-service: "http://localhost:9004"
  mail-send-service: "http://localhost:9005"
  car-history-service: "http://localhost:9006"
