server:
  port: 8084
  error:
    include-message: always
spring:
  application:
    name: mail-process-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: localhost
    port: 15672
    password: password
    username: user
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
        mode: service
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # TODO make it update when "ready"

management:
  endpoints:
    web:
      exposure:
        # TODO *
        include: prometheus

rabbitmq:
  queue:
    name: mail-process-queue
  exchange:
    name: mail-process-exchange
  routing:
    key: mail-process-routing-key

mail:
  send:
    exchange: mail-send-exchange
  routing:
    key: mail-send-routing-key
