apiVersion: v1
kind: Secret
metadata:
  name: mail-send-secret
  #TODO at least base64
stringData:
  #TODO add USERNAME
  #  SPRING.MAIL.USERNAME:
  #TODO add PASSWORD
  #  SPRING.MAIL.PASSWORD:

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/project"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: ""

  SPRING_RABBITMQ_ADDRESSES: "rabbitmq"
  SPRING_RABBITMQ_PORT: "15672"
  SPRING_RABBITMQ_USERNAME: "user"
  SPRING_RABBITMQ_PASSWORD: ""

type: Opaque
