apiVersion: v1
kind: Service
metadata:
  name: mail-send
  labels:
    app: mail-send
    spring-boot: "true"
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8183"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: mail-send
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    #      protocol: TCP
    - name: actuator
      port: 8183
      targetPort: 8183
