apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access": "proxy",
          "editable": true,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://prometheus-service.monitoring.svc:9090",
          "version": 1
        },
        {
          "access": "proxy",
          "editable": true,
          "name": "tempo",
          "orgId": 1,
          "type": "tempo",
          "url": "http://tempo.monitoring.svc:3200",
          "version": 1
        },
        {
          "access": "proxy",
          "editable": true,
          "name": "promtail",
          "orgId": 1,
          "type": "promtail",
          "url": "http://promtail.monitoring.svc:9080",
          "version": 1
        },
        {
          "access": "proxy",
          "editable": true,
          "name": "loki",
          "orgId": 1,
          "type": "loki",
          "url": "http://loki.monitoring.svc:3100",
          "version": 1
        }
      ]
    }
    
    
    
    
    
