apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: grafana-volume # Sets PV name
  namespace: monitoring
  labels:
    type: local # Sets PV's type
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/grafana" # Sets PV's host path
  # chmod 472 /mnt/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: grafana-volume-claim # Sets PVC's name
  namespace: monitoring
  labels:
    app: grafana # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi # Sets PVC's size
