server:
  port: 8085
  error:
    include-message: always
spring:
  application:
    name: car-history-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diploma_project?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: 127.0.0.1
    port: 15672
    username: user
    password: password
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # TODO make it update when "ready"
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
        mode: service
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        # TODO *
        include: prometheus

rabbitmq:
  queue:
    name: mail-process-queue
  exchange:
    name: mail-process-exchange
  routing:
    key: mail-process-routing-key

springdoc:
  api-docs:
      path: "/docs/api"
  swagger-ui:
    path: "/docs/swagger-ui"

frontEnd:
  # TODO change for prod
  url: http://localhost:4200
